definitions:
  dto.CheckPasswordReset:
    properties:
      email:
        type: string
      redirectUrl:
        type: string
    required:
    - email
    - redirectUrl
    type: object
  dto.CreateCategoryRequest:
    properties:
      category_name:
        type: string
    required:
    - category_name
    type: object
  dto.CreateDepartmentRequest:
    properties:
      department_name:
        type: string
      location_id:
        type: integer
    required:
    - department_name
    - location_id
    type: object
  dto.CreateLocationRequest:
    properties:
      location_name:
        type: string
    required:
    - location_name
    type: object
  dto.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.UpdateInformationUserRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    required:
    - first_name
    - last_name
    type: object
  dto.UpdateRoleUserRequest:
    properties:
      role_title:
        type: string
    required:
    - role_title
    type: object
  dto.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserRegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      redirectUrl:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - redirectUrl
    type: object
  dto.UserRequestResetPassword:
    properties:
      new_password:
        type: string
      token:
        type: string
    required:
    - new_password
    - token
    type: object
info:
  contact: {}
paths:
  /api/assets:
    get:
      consumes:
      - application/json
      description: Get all assets
      produces:
      - application/json
      responses: {}
      summary: Get all assets
      tags:
      - assets
    post:
      consumes:
      - multipart/form-data
      description: Create assets
      parameters:
      - description: Asset Name
        in: formData
        name: asset_name
        required: true
        type: string
      - description: Purchase Date (RFC3339 format, e.g. 2023-04-15T10:00:00Z)
        in: formData
        name: purchase_date
        required: true
        type: string
      - description: Cost
        in: formData
        name: cost
        required: true
        type: number
      - description: Owner ID
        in: formData
        name: owner
        type: integer
      - description: Warranty Expiry (RFC3339 format, e.g. 2023-12-31T23:59:59Z)
        in: formData
        name: warrant_expiry
        required: true
        type: string
      - description: Serial Number
        in: formData
        name: serial_number
        required: true
        type: string
      - description: Category ID
        in: formData
        name: category_id
        required: true
        type: integer
      - description: Department ID
        in: formData
        name: department_id
        required: true
        type: integer
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Image to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Create assets
      tags:
      - assets
    put:
      consumes:
      - multipart/form-data
      description: Update assets
      parameters:
      - description: Asset Name
        in: formData
        name: asset_name
        required: true
        type: string
      - description: Purchase Date (RFC3339 format, e.g. 2023-04-15T10:00:00Z)
        in: formData
        name: purchase_date
        required: true
        type: string
      - description: Cost
        in: formData
        name: cost
        required: true
        type: number
      - description: Owner ID
        in: formData
        name: owner
        type: integer
      - description: Warranty Expiry (RFC3339 format, e.g. 2023-12-31T23:59:59Z)
        in: formData
        name: warrant_expiry
        required: true
        type: string
      - description: Maintenance (RFC3339 format, e.g. 2023-12-31T23:59:59Z)
        in: formData
        name: maintenance
        required: true
        type: string
      - description: Serial Number
        in: formData
        name: serial_number
        required: true
        type: string
      - description: Serial Number
        in: formData
        name: status
        required: true
        type: string
      - description: Category ID
        in: formData
        name: category_id
        required: true
        type: integer
      - description: Department ID
        in: formData
        name: department_id
        required: true
        type: integer
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Image to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Update assets
      tags:
      - assets
  /api/assets/{id}:
    delete:
      consumes:
      - application/json
      description: Delete assets
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete assets
      tags:
      - assets
    get:
      consumes:
      - application/json
      description: Get assets
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get assets
      tags:
      - assets
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Login
      tags:
      - auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses: {}
      summary: Logout
      tags:
      - auth
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh Token
      parameters:
      - description: Data
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshRequest'
      produces:
      - application/json
      responses: {}
      summary: Refresh Token
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: Register user
      tags:
      - auth
  /api/categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      produces:
      - application/json
      responses: {}
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create categories
      parameters:
      - description: Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCategoryRequest'
      produces:
      - application/json
      responses: {}
      summary: Create categories
      tags:
      - categories
  /api/categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete category via id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete category
      tags:
      - categories
  /api/departments:
    get:
      consumes:
      - application/json
      description: Get all departments
      produces:
      - application/json
      responses: {}
      summary: Get all departments
      tags:
      - departments
    post:
      consumes:
      - application/json
      description: Create departments
      parameters:
      - description: Data
        in: body
        name: department
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDepartmentRequest'
      produces:
      - application/json
      responses: {}
      summary: Create departments
      tags:
      - departments
  /api/departments/{id}:
    delete:
      consumes:
      - application/json
      description: Delete department via id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete department
      tags:
      - departments
  /api/locations:
    get:
      consumes:
      - application/json
      description: Get all location
      produces:
      - application/json
      responses: {}
      summary: Get all location
      tags:
      - locations
    post:
      consumes:
      - application/json
      description: Create location
      parameters:
      - description: Data
        in: body
        name: location
        required: true
        schema:
          $ref: '#/definitions/dto.CreateLocationRequest'
      produces:
      - application/json
      responses: {}
      summary: Create Location
      tags:
      - locations
  /api/locations/{id}:
    delete:
      consumes:
      - application/json
      description: Delete location via id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete location
      tags:
      - locations
  /api/roles:
    get:
      consumes:
      - application/json
      description: GetRole
      produces:
      - application/json
      responses: {}
      summary: GetRole
      tags:
      - users
  /api/user/{email}:
    delete:
      consumes:
      - application/json
      description: Delete user via email
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete user
      tags:
      - users
  /api/user/forget-password:
    post:
      consumes:
      - application/json
      description: Email reset password
      parameters:
      - description: Data
        in: body
        name: Email_Reset_Password
        required: true
        schema:
          $ref: '#/definitions/dto.CheckPasswordReset'
      produces:
      - application/json
      responses: {}
      summary: Email reset password
      tags:
      - users
  /api/user/information:
    patch:
      consumes:
      - application/json
      description: Update Information
      parameters:
      - description: Data
        in: body
        name: Information
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateInformationUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Update Information
      tags:
      - users
  /api/user/password-reset:
    patch:
      consumes:
      - application/json
      description: reset password
      parameters:
      - description: Data
        in: body
        name: Password-reset
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestResetPassword'
      produces:
      - application/json
      responses: {}
      summary: Password-reset
      tags:
      - users
  /api/user/role:
    patch:
      consumes:
      - application/json
      description: Update Role
      parameters:
      - description: Data
        in: body
        name: Role
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateRoleUserRequest'
      produces:
      - application/json
      responses: {}
      summary: Update Role
      tags:
      - users
  /api/user/session:
    get:
      consumes:
      - application/json
      description: Get session
      produces:
      - application/json
      responses: {}
      summary: Get session
      tags:
      - users
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all user
      produces:
      - application/json
      responses: {}
      summary: Get all user
      tags:
      - users
swagger: "2.0"
